### ISSUE TITLE
Ta vazio aqui em

### ISSUE THREAD

**Issue by heitorfreitasferreira** [nayaranunes/gerencia-pontos-cartesianos#1]
cóe menó da o push nessa porra logo 😳😳

**Comment by nayaranunes** [comment]
Esqueci que agora é main e não master 🤡

**Comment by heitorfreitasferreira** [comment]
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK

Caiu no conto da maicrosófit dona do github
